version: '3.6'

services:
    rabbitmq:
      image: "rabbitmq:3.13-rc-management"  # Pulls the image from DockerHub if not in local
      container_name: rabbitmq_container    # Defines container's name
      ports:
        - "5672:5672"  # AMQP
        - "15672:15672"  # Management UI
      environment:
        RABBITMQ_DEFAULT_USER: guest  # Sets RabbitMQ's login credentials
        RABBITMQ_DEFAULT_PASS: guest  # Sets RabbitMQ's login credentials