version: '3.6'

services:

  eureka-server:
    build: eureka-server
    ports:
      - "8761:8761"

#  notification:
#    build: notification
#    depends_on:
      #- eureka-server
      #- rabbitmq
#    ports:
#      - "8087:8087"

  login:
    build: login
    depends_on:
      - eureka-server
    ports:
      - "8090:8090"

#  amazon:
#    build: amazon
#    depends_on:
#      #- eureka-server
#      - rabbitmq
#      #- notification
#    ports:
#      - "8082:8082"
#    command: bash -c "while ! nc -z rabbitmq 5672; do echo 'Waiting for RabbitMQ'; sleep 3; done && java -cp /amazon-0.0.1.jar AmazonApplication"
#    #command: ["./Wait.sh", "rabbitmq:5672", "--", "java", "-jar", "/amazon-0.0.1.jar"]
    #restart: on-failure


#  apple:
#    build: apple
#    depends_on:
#      - eureka-server
#      - rabbitmq
#      #- notification
#    command: bash -c "while ! nc -z rabbitmq 5672; do echo 'Waiting for RabbitMQ'; sleep 3; done && java -cp /apple-0.0.1.jar AppleApplication"
#    restart: on-failure

#  facebook:
#    build: facebook
#    depends_on:
#      - eureka-server
#      - rabbitmq
#      #- notification
##    command: bash -c "while ! nc -z rabbitmq 5672; do echo 'Waiting for RabbitMQ'; sleep 3; done && java -cp /facebook-0.0.1.jar FacebookApplication"
##    restart: on-failure
#
#
#  google:
#    build: google
#    depends_on:
#      - eureka-server
#      - rabbitmq
#      #- notification
##    command: bash -c "while ! nc -z rabbitmq 5672; do echo 'Waiting for RabbitMQ'; sleep 3; done && java -cp /google-0.0.1.jar GoogleApplication"
##    restart: on-failure
#
#
#  netflix:
#    build: netflix
#    depends_on:
#      - eureka-server
#      - rabbitmq
      #- notification
#    command: bash -c "while ! nc -z rabbitmq 5672; do echo 'Waiting for RabbitMQ'; sleep 3; done && java -cp /netflix-0.0.1.jar NetflixApplication"
#    restart: on-failure


#  employee:
#    build: employee
#    environment:
#      NAME: employee
#    depends_on:
#      - eureka-server
#      - rabbitmq
#      - login
#      - notification
#      - amazon
##      - apple
##      - facebook
##      - google
##      - netflix
#    ports:
#      - "8080:8080"




